#! /bin/bash

#cd
template='templates/reports/DisableXmlDocs.xslt'
#rm .github/workflows/codeql-analysis.yml
#echo -P ubuntu-latest=nektos/act-environments-ubuntu:18.04>.actrc

for f in src/*/*.csproj; do
	xsltproc $template $f >$f.tmp
	mv $f.tmp $f
done

