namespace BinaryDataDecoders.LanC
{
    public enum LanCCommandCameraSpecial : byte
    {
        ZoomTelephotoSlowest = 0x0,
        ZoomTelephoto1 = 0x2,
        ZoomTelephoto2 = 0x4,
        ZoomTelephoto3 = 0x6,
        ZoomTelephoto4 = 0x8,
        ZoomTelephoto5 = 0x0A,
        ZoomTelephoto6 = 0x0C,
        ZoomTelephotoFastest = 0x0E,
        ZoomWideSlowest = 0x10,
        ZoomWide1 = 0x12,
        ZoomWide2 = 0x14,
        ZoomWide3 = 0x16,
        ZoomWide4 = 0x18,
        ZoomWide5 = 0x1A,
        ZoomWide6 = 0x1C,
        ZoomWideFastest = 0x1E,
        Grid = 0x21,
        Faster = 0x25,
        RecordStart = 0x27,
        RecordStop = 0x29,
        ZoomTelephotoSlowest_NoDigital = 0x30,
        ZoomTelephoto1_NoDigital = 0x32,
        ZoomTelephoto2_NoDigital = 0x34,
        ZoomTelephotoSlow = 0x35,
        ZoomTelephoto3_NoDigital = 0x36,
        ZoomWideSlow = 0x37,
        ZoomTelephoto4_NoDigital = 0x38,
        ZoomTelephoto7 = 0x39,
        ZoomTelephoto5_NoDigital = 0x3A,
        ZoomWideFast = 0x3B,
        ZoomTelephoto6_NoDigital = 0x3C,
        ZoomTelephotoFastest_NoDigital = 0x3E,
        AutoFocusToggle = 0x41,
        FocusFar = 0x45,
        FocusNear = 0x47,
        WhiteBalanceToggle = 0x49,
        BacklightDv = 0x4B,
        Backlight = 0x51,
        IrisClose = 0x53,
        IrisOpen = 0x55,
        Shutter = 0x61,
        WhiteBalanceReset = 0x77,
        MemoryImpose = 0x85,
        ColorMode = 0x87,
        SuperImpose = 0x89,
        IrisAuto = 0xAF,
    }
}
/*
 * http://www.boehmel.de/lanc.htm#byte0
 */
